name: Format

on:
  pull_request:
  push:
    branches:
      - new-stuff

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: actionsx/prettier@v2
        with:
          args: --check .